/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check service health including database connectivity.
         *
         *     Returns HTTP 503 with an error detail if the database is unreachable.
         *     Never returns 200 with a degraded payload — fail loud.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{ticker}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Price Series
         * @description Return the EOD price series for *ticker*, ingesting on demand if cold/stale.
         */
        get: operations["get_price_series_stocks__ticker__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{ticker}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Analysis
         * @description Render-ready analysis payload for one ticker — single call, no frontend finance.
         *
         *     The visible range ends at the last trading day available for the ticker;
         *     rolling series are warmed up on a pre-range pad and sliced back to the
         *     visible range. All fractional fields are decimal fractions (0.05 = 5%).
         */
        get: operations["get_stock_analysis_stocks__ticker__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{ticker}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ticker News
         * @description Per-ticker news, newest first — DB-first with a declared degrade path.
         *
         *     Degrade decision (deliberate, documented): news is a SECONDARY panel.  If
         *     the Tiingo refresh fails but the DB holds cached articles, serve them with
         *     ``stale=true`` and log the error — a declared degradation, NOT a silent
         *     fallback.  If the refresh fails and the cache is empty, fail loud with the
         *     usual 503/502 mapping.
         *
         *     Unknown tickers do not 404 here: Tiingo's news feed has no per-ticker
         *     existence check, and "no news" is a legitimate ``count=0`` response.  The
         *     ticker format is sanity-checked (alphanumeric + ".-", at most 10 chars)
         *     to reject absurd path segments with 422.
         */
        get: operations["get_ticker_news_stocks__ticker__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Portfolio
         * @description Render-ready analysis payload for an ad-hoc portfolio — single call.
         *
         *     Buy-and-hold replay (NAV, returns-based stats, benchmark comparison) plus
         *     covariance decomposition (risk contributions, diversification ratio,
         *     correlation matrix) — see ``app.analytics.portfolio`` for the two-views
         *     semantics. All fractional fields are decimal fractions (0.05 = 5%).
         */
        post: operations["analyze_portfolio_portfolio_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Portfolios
         * @description List portfolios (id order), hard-capped at the service's LIST_HARD_CAP.
         */
        get: operations["list_portfolios_portfolios_get"];
        put?: never;
        /**
         * Create Portfolio
         * @description Create a portfolio with optional initial positions.
         *
         *     Position tickers are validated against Tiingo via the EOD ensure — a typo
         *     fails loud (404) BEFORE anything is persisted — which also warms the EOD
         *     cache for the overview.
         */
        post: operations["create_portfolio_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio
         * @description One portfolio with its positions (sorted by ticker).
         */
        get: operations["get_portfolio_portfolios__portfolio_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Portfolio
         * @description Delete a portfolio; its positions cascade away at the DB level.
         */
        delete: operations["delete_portfolio_portfolios__portfolio_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Portfolio
         * @description Partially update name and/or cash.
         */
        patch: operations["patch_portfolio_portfolios__portfolio_id__patch"];
        trace?: never;
    };
    "/portfolios/{portfolio_id}/positions/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Position
         * @description Upsert one position.
         *
         *     INSERT path validates the ticker against Tiingo (and warms the EOD cache);
         *     the UPDATE path deliberately does NOT re-ensure — the ticker was already
         *     validated when the position was created.
         */
        put: operations["put_position_portfolios__portfolio_id__positions__ticker__put"];
        post?: never;
        /**
         * Delete Position
         * @description Delete one position; 404 covers both a missing portfolio and a missing ticker.
         */
        delete: operations["delete_position_portfolios__portfolio_id__positions__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio Overview
         * @description Render-ready position table with P&L and column-header aggregates (D6).
         *
         *     Last/prev closes come from the two most recent eod_prices rows per ticker;
         *     the EOD ensure runs first so stale tickers are refreshed.  An empty
         *     portfolio is a legitimate 200 with zeroed/null aggregates.
         */
        get: operations["get_portfolio_overview_portfolios__portfolio_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolios/{portfolio_id}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio News
         * @description Aggregated news across all portfolio tickers, newest first.
         *
         *     Staleness is checked per ticker but all stale tickers are refreshed with
         *     ONE combined Tiingo call (see ``ensure_news``).  Degrade path mirrors
         *     GET /stocks/{ticker}/news exactly: refresh failure with cached articles
         *     serves them with ``stale=true``; with an empty cache it fails loud.
         */
        get: operations["get_portfolio_news_portfolios__portfolio_id__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scenario
         * @description Historical replay of a persisted portfolio over an explicit window.
         *
         *     Stacked value/weight/performance series plus a typed statistics rail —
         *     render-ready in one call. All fractional fields are decimal fractions
         *     (0.05 = 5%).
         */
        post: operations["scenario_statistics_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/beta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Beta Scatter
         * @description Daily-return scatter + OLS regression of two pseudo-assets (y on x).
         */
        post: operations["beta_scatter_statistics_beta_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/correlation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rolling Correlation
         * @description Rolling correlation of two pseudo-assets, warm from the window start.
         */
        post: operations["rolling_correlation_statistics_correlation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/statistics/stock-correlation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stock Correlation
         * @description Pairwise correlation matrix of a portfolio's holdings (trailing window).
         */
        post: operations["stock_correlation_statistics_stock_correlation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AllocationOut
         * @description Resolved allocation at the first analyzed date (the replay strike point).
         */
        AllocationOut: {
            /** Positions */
            positions: components["schemas"]["AllocationPosition"][];
            /**
             * Initial Nav
             * @description Sum of initial position values, in currency units.
             */
            initial_nav: number;
        };
        /**
         * AllocationPosition
         * @description One position of the resolved allocation at the first date.
         */
        AllocationPosition: {
            /** Ticker */
            ticker: string;
            /**
             * Weight
             * @description Effective initial weight as a decimal fraction (0.5 = 50%), never 0-100. For mode='weights' the (renormalized) requested weight; for mode='quantities' the initial-date value weight.
             */
            weight: number;
            /**
             * Initial Value
             * @description Position value at the first date, in currency units.
             */
            initial_value: number;
        };
        /**
         * AnalysisHeader
         * @description Render-ready header strip values (RAW, un-adjusted prices).
         */
        AnalysisHeader: {
            /** Ticker */
            ticker: string;
            /**
             * Name
             * @description Instrument name from Tiingo metadata, if known.
             */
            name: string | null;
            /**
             * Last Close
             * @description Most recent RAW close price (currency units).
             */
            last_close: number;
            /**
             * Prev Close
             * @description Previous trading day's RAW close price (currency units).
             */
            prev_close: number;
            /**
             * Change
             * @description last_close - prev_close, in currency units (not a fraction).
             */
            change: number;
            /**
             * Change Pct
             * @description One-day change as a decimal fraction (0.05 = 5%), never 0-100.
             */
            change_pct: number;
            /**
             * As Of
             * Format: date
             * @description Date of last_close.
             */
            as_of: string;
        };
        /**
         * AnalysisParams
         * @description Echo of the resolved request parameters.
         */
        AnalysisParams: {
            /**
             * Range
             * @description Requested range preset.
             * @enum {string}
             */
            range: "1M" | "6M" | "1Y" | "5Y" | "MAX";
            /**
             * Benchmark
             * @description Benchmark ticker used for beta/correlation/relative series.
             */
            benchmark: string;
            /**
             * Window
             * @description Rolling window length in TRADING days.
             */
            window: number;
            /**
             * Start Date
             * Format: date
             * @description Resolved visible-range start (inclusive for prices/candles).
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description Resolved visible-range end — the last trading day available for the ticker.
             */
            end_date: string;
        };
        /**
         * AnalysisStats
         * @description Point statistics over IN-RANGE returns only (the rolling warm-up pad
         *     is never included). Beta/correlation are versus the benchmark on the
         *     aligned in-range date grid.
         */
        AnalysisStats: {
            /**
             * Annualized Volatility
             * @description Annualized volatility as a decimal fraction (0.25 = 25%), never 0-100.
             */
            annualized_volatility: number;
            /**
             * Var 95
             * @description Historical 1-day VaR at 95% as a POSITIVE decimal fraction (0.02 = 5% of days lose more than 2%), never 0-100.
             */
            var_95: number;
            /**
             * Var 99
             * @description Historical 1-day VaR at 99% as a POSITIVE decimal fraction, never 0-100.
             */
            var_99: number;
            /**
             * Cvar 95
             * @description Historical 1-day CVaR (expected shortfall) at 95% as a POSITIVE decimal fraction, never 0-100.
             */
            cvar_95: number;
            /**
             * Total Return
             * @description Compounded in-range total return as a decimal fraction (0.5 = +50%), never 0-100.
             */
            total_return: number;
            /**
             * Beta
             * @description Beta vs benchmark over in-range aligned returns (unitless).
             */
            beta: number;
            /**
             * Correlation
             * @description Pearson correlation vs benchmark over in-range aligned returns (-1..1).
             */
            correlation: number;
            max_drawdown: components["schemas"]["DrawdownOut"];
            best_day: components["schemas"]["DatedValue"];
            worst_day: components["schemas"]["DatedValue"];
        };
        /**
         * AxisLabels
         * @description Display labels for the two compared pseudo-assets.
         */
        AxisLabels: {
            /**
             * X
             * @description Label of asset_x: the ticker, or the portfolio name.
             */
            x: string;
            /**
             * Y
             * @description Label of asset_y: the ticker, or the portfolio name.
             */
            y: string;
        };
        /**
         * BenchmarkComparison
         * @description Cumulative return of the portfolio vs the benchmark, rebased to 0.
         *
         *     Both series share the same aligned date grid and start at exactly 0.0 on
         *     the same first date. Values are decimal fractions (0.05 = 5%), never 0-100.
         */
        BenchmarkComparison: {
            /**
             * Portfolio
             * @description [date, cumulative return] points; decimal fractions (0.05 = 5%).
             */
            portfolio: [
                string,
                number
            ][];
            /**
             * Benchmark
             * @description [date, cumulative return] points; decimal fractions (0.05 = 5%).
             */
            benchmark: [
                string,
                number
            ][];
        };
        /**
         * BetaRequest
         * @description Regression of asset_y's daily returns on asset_x's over the window.
         */
        BetaRequest: {
            /**
             * Start Date
             * Format: date
             * @description Window start (inclusive).
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description Window end (inclusive).
             */
            end_date: string;
            /**
             * Asset X
             * @description X-axis / independent pseudo-asset.
             */
            asset_x: components["schemas"]["TickerRef"] | components["schemas"]["PortfolioRef"];
            /**
             * Asset Y
             * @description Y-axis / dependent pseudo-asset.
             */
            asset_y: components["schemas"]["TickerRef"] | components["schemas"]["PortfolioRef"];
        };
        /**
         * BetaResponse
         * @description Scatter + regression of two pseudo-assets' daily returns.
         */
        BetaResponse: {
            labels: components["schemas"]["AxisLabels"];
            /**
             * Scatter
             * @description [ret_x, ret_y] aligned daily return pairs, decimal fractions.
             */
            scatter: [
                number,
                number
            ][];
            regression: components["schemas"]["RegressionOut"];
            /**
             * Regression Line
             * @description Two endpoints of the fitted line, y = alpha + beta * x evaluated at min(ret_x) and max(ret_x) — render-ready.
             */
            regression_line: [
                number,
                number
            ][];
        };
        /**
         * Candle
         * @description One OHLCV candle built from RAW (un-adjusted) prices.
         *
         *     Daily for ranges up to 5Y; weekly (W-FRI buckets: open=first, high=max,
         *     low=min, close=last, volume=sum) for range MAX.
         */
        Candle: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /**
         * CorrelationMatrixOut
         * @description Pairwise Pearson correlation of per-asset daily returns.
         */
        CorrelationMatrixOut: {
            /**
             * Tickers
             * @description Row/column order of the matrix.
             */
            tickers: string[];
            /**
             * Matrix
             * @description Row-major square matrix (-1..1); symmetric with unit diagonal.
             */
            matrix: number[][];
        };
        /**
         * CorrelationRequest
         * @description Rolling correlation of two pseudo-assets' daily returns.
         */
        CorrelationRequest: {
            /**
             * Start Date
             * Format: date
             * @description Window start (inclusive).
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description Window end (inclusive).
             */
            end_date: string;
            /**
             * Asset X
             * @description X-axis / independent pseudo-asset.
             */
            asset_x: components["schemas"]["TickerRef"] | components["schemas"]["PortfolioRef"];
            /**
             * Asset Y
             * @description Y-axis / dependent pseudo-asset.
             */
            asset_y: components["schemas"]["TickerRef"] | components["schemas"]["PortfolioRef"];
            /**
             * Window
             * @description Rolling window length in TRADING days.
             * @default 63
             */
            window: number;
        };
        /**
         * CorrelationResponse
         * @description Rolling-correlation series of two pseudo-assets.
         *
         *     Returns are warmed up on a pre-start lookback pad (the F2.2 pattern) so the
         *     series covers the requested window from (approximately) its first trading
         *     day; NaN warm-up rows are dropped.
         */
        CorrelationResponse: {
            labels: components["schemas"]["AxisLabels"];
            /**
             * Window
             * @description Rolling window length in TRADING days.
             */
            window: number;
            /**
             * Series
             * @description [date, correlation] points (-1..1); in-range dates only.
             */
            series: [
                string,
                number
            ][];
            /**
             * Current
             * @description Most recent rolling correlation (last point).
             */
            current: number;
        };
        /**
         * CumulativeReturns
         * @description Cumulative return series rebased to 0 at the first in-range date.
         *
         *     Asset and benchmark share the same date grid (aligned on common trading
         *     days before slicing). Values are decimal fractions (0.05 = 5%), never
         *     0-100; both series start at exactly 0.0 on the same first date.
         */
        CumulativeReturns: {
            /**
             * Asset
             * @description [date, cumulative return] points; decimal fractions (0.05 = 5%).
             */
            asset: [
                string,
                number
            ][];
            /**
             * Benchmark
             * @description [date, cumulative return] points; decimal fractions (0.05 = 5%).
             */
            benchmark: [
                string,
                number
            ][];
        };
        /**
         * DatedNav
         * @description A single dated NAV observation, in currency units.
         */
        DatedNav: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Value
             * @description Portfolio value in currency units (not a fraction).
             */
            value: number;
        };
        /**
         * DatedValue
         * @description A single dated return observation.
         */
        DatedValue: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Value
             * @description Daily return as a decimal fraction (0.05 = 5%), never 0-100.
             */
            value: number;
        };
        /**
         * DrawdownOut
         * @description Maximum drawdown of the in-range ADJUSTED close series.
         */
        DrawdownOut: {
            /**
             * Depth
             * @description NEGATIVE decimal fraction (-0.35 = 35% peak-to-trough loss), never 0-100.
             */
            depth: number;
            /**
             * Peak Date
             * Format: date
             */
            peak_date: string;
            /**
             * Trough Date
             * Format: date
             */
            trough_date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /**
         * HistogramOut
         * @description Histogram of in-range daily returns.
         */
        HistogramOut: {
            /**
             * Bin Edges
             * @description len(counts)+1 edges in daily-return units, decimal fractions (0.05 = 5%).
             */
            bin_edges: number[];
            /**
             * Counts
             * @description Observations per bin.
             */
            counts: number[];
            /**
             * Counts Normalized
             * @description Each count divided by the maximum count (0-1), for direct bar heights.
             */
            counts_normalized: number[];
        };
        /**
         * NewsArticle
         * @description One news article linked to the requested ticker.
         */
        NewsArticle: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Source */
            source: string | null;
            /** Description */
            description: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /**
         * NewsResponse
         * @description News articles for one ticker, newest first.
         *
         *     ``stale`` is True when the Tiingo refresh failed but cached articles were
         *     served — a declared degradation, never a silent fallback.
         */
        NewsResponse: {
            /** Ticker */
            ticker: string;
            /** Count */
            count: number;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Items */
            items: components["schemas"]["NewsArticle"][];
        };
        /**
         * OverviewAggregates
         * @description Portfolio-level aggregates rendered in the table column headers (D6).
         */
        OverviewAggregates: {
            /**
             * Total Market Value
             * @description Sum of position market values, currency units (0 when empty).
             */
            total_market_value: number;
            /**
             * Total Cost Basis
             * @description Sum over positions with a known acq_price; null when ALL are unknown.
             */
            total_cost_basis: number | null;
            /**
             * Total Pnl
             * @description Sum of pnl over positions with a known acq_price; null when no position has a cost basis.
             */
            total_pnl: number | null;
            /**
             * Total Pnl Pct
             * @description total_pnl / total_cost_basis as a decimal fraction, never 0-100; null when no position has a cost basis.
             */
            total_pnl_pct: number | null;
            /**
             * Cash
             * @description Uninvested cash balance, currency units.
             */
            cash: number;
            /**
             * Total Value
             * @description total_market_value + cash, currency units.
             */
            total_value: number;
            /**
             * As Of
             * @description Max as_of across positions; null for an empty portfolio.
             */
            as_of: string | null;
        };
        /**
         * PortfolioAnalysisRequest
         * @description Ad-hoc portfolio definition to replay and decompose (no persistence).
         */
        PortfolioAnalysisRequest: {
            /**
             * Positions
             * @description Between 2 and 50 positions.
             */
            positions: components["schemas"]["PositionIn"][];
            /**
             * Mode
             * @description 'weights' = every position carries a weight; 'quantities' = share counts.
             * @enum {string}
             */
            mode: "weights" | "quantities";
            /**
             * Range
             * @description Visible-range preset; MAX = full COMMON history.
             * @default 1Y
             * @enum {string}
             */
            range: "1M" | "6M" | "1Y" | "5Y" | "MAX";
            /**
             * Benchmark
             * @description Benchmark ticker for the comparison series and beta/correlation. May coincide with a position.
             * @default SPY
             */
            benchmark: string;
        };
        /**
         * PortfolioAnalysisResponse
         * @description Render-ready single-call payload for the static portfolio page.
         *
         *     Two views, two questions (see ``app.analytics.portfolio``): ``nav``,
         *     ``benchmark_comparison`` and the return-based ``stats`` are a buy-and-hold
         *     REPLAY (fixed quantities, weights drift); ``risk_contributions`` and
         *     ``diversification_ratio`` are a covariance DECOMPOSITION at the effective
         *     initial weights held constant. The backend computes ALL finance; the
         *     frontend only draws. Every fractional field is a decimal fraction
         *     (0.05 = 5%), never 0-100.
         */
        PortfolioAnalysisResponse: {
            params: components["schemas"]["PortfolioParams"];
            allocation: components["schemas"]["AllocationOut"];
            /**
             * Nav
             * @description [date, NAV] points in currency units; starts at initial_nav. Daily up to 5Y; weekly (W-FRI, last-of-week) for range MAX. Shares the same date grid as benchmark_comparison (sliced to the portfolio–benchmark aligned index) so all line series can be plotted on a single x-axis. Stats are computed on the full position-grid NAV (before the benchmark alignment slice) — they describe the portfolio, not the comparison chart.
             */
            nav: [
                string,
                number
            ][];
            benchmark_comparison: components["schemas"]["BenchmarkComparison"];
            stats: components["schemas"]["PortfolioStats"];
            correlation_matrix: components["schemas"]["CorrelationMatrixOut"];
            /**
             * Risk Contributions
             * @description Per-asset fractions of total risk; they sum to 1.
             */
            risk_contributions: components["schemas"]["RiskContributionOut"][];
            histogram: components["schemas"]["HistogramOut"];
        };
        /**
         * PortfolioCreate
         * @description Body for POST /portfolios.
         */
        PortfolioCreate: {
            /**
             * Name
             * @description Portfolio name; 1..80 characters after trimming, unique across the installation.
             */
            name: string;
            /**
             * Cash
             * @description Uninvested cash, currency units.
             * @default 0
             */
            cash: number;
            /**
             * Positions
             * @description Initial positions (at most 50); tickers must be unique.
             */
            positions?: components["schemas"]["PositionCreate"][];
        };
        /**
         * PortfolioListItem
         * @description One row of GET /portfolios (positions omitted, count only).
         */
        PortfolioListItem: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Cash */
            cash: number;
            /** Position Count */
            position_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PortfolioNewsResponse
         * @description Aggregated news across all portfolio tickers, newest first.
         *
         *     ``stale`` is True when the Tiingo refresh failed but cached articles were
         *     served — a declared degradation, never a silent fallback (same contract
         *     as GET /stocks/{ticker}/news).
         */
        PortfolioNewsResponse: {
            /** Portfolio Id */
            portfolio_id: number;
            /**
             * Tickers
             * @description Portfolio tickers the articles were matched on.
             */
            tickers: string[];
            /** Count */
            count: number;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Items */
            items: components["schemas"]["NewsArticle"][];
        };
        /**
         * PortfolioOut
         * @description One persisted portfolio with its positions (sorted by ticker).
         */
        PortfolioOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Cash */
            cash: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
        };
        /**
         * PortfolioOverviewResponse
         * @description Render-ready overview for GET /portfolios/{id}/overview.
         */
        PortfolioOverviewResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Positions */
            positions: components["schemas"]["PositionOverview"][];
            aggregates: components["schemas"]["OverviewAggregates"];
        };
        /**
         * PortfolioParams
         * @description Echo of the resolved request parameters.
         */
        PortfolioParams: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "weights" | "quantities";
            /**
             * Range
             * @description Requested range preset.
             * @enum {string}
             */
            range: "1M" | "6M" | "1Y" | "5Y" | "MAX";
            /**
             * Benchmark
             * @description Benchmark ticker used for the comparison series.
             */
            benchmark: string;
            /**
             * Start Date
             * Format: date
             * @description First trading day of the analyzed window (first date where ALL position tickers have data).
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description Last trading day of the analyzed window — the most recent date COMMON to all requested symbols (positions + benchmark). One stale symbol (a ticker whose last available EOD row lags the others) moves this date back for everyone; end = min(last_available_date per symbol).
             */
            end_date: string;
            /**
             * Initial Nav
             * @description Portfolio value at start_date, in currency units. 10000 for mode='weights' (notional); the actual position value for mode='quantities'.
             */
            initial_nav: number;
        };
        /**
         * PortfolioPatch
         * @description Body for PATCH /portfolios/{id} — at least one field must be present.
         */
        PortfolioPatch: {
            /**
             * Name
             * @description New portfolio name (same rules as on create).
             */
            name?: string | null;
            /**
             * Cash
             * @description New cash balance, currency units.
             */
            cash?: number | null;
        };
        /**
         * PortfolioRef
         * @description Pseudo-asset reference: a persisted portfolio.
         *
         *     Resolved by replaying the portfolio's CURRENT quantities over the request
         *     window (buy-and-hold historical replay — see ``app.analytics.portfolio``).
         *     The pseudo-asset's daily returns are the engine's ``portfolio_returns``
         *     over the inner-joined holdings (uninvested cash is NOT part of the
         *     pseudo-asset — it is constant and would only dilute beta/correlation).
         */
        PortfolioRef: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "portfolio";
            /**
             * Id
             * @description Persisted portfolio id.
             */
            id: number;
        };
        /**
         * PortfolioStats
         * @description Point statistics over the portfolio's daily returns in the analyzed
         *     window. Beta/correlation are versus the benchmark on the aligned date
         *     grid; the diversification ratio is evaluated at the effective initial
         *     weights (decomposition view).
         */
        PortfolioStats: {
            /**
             * Annualized Volatility
             * @description Annualized volatility as a decimal fraction (0.25 = 25%), never 0-100.
             */
            annualized_volatility: number;
            /**
             * Var 95
             * @description Historical 1-day VaR at 95% as a POSITIVE decimal fraction (0.02 = 5% of days lose more than 2%), never 0-100.
             */
            var_95: number;
            /**
             * Var 99
             * @description Historical 1-day VaR at 99% as a POSITIVE decimal fraction, never 0-100.
             */
            var_99: number;
            /**
             * Cvar 95
             * @description Historical 1-day CVaR (expected shortfall) at 95% as a POSITIVE decimal fraction, never 0-100.
             */
            cvar_95: number;
            /**
             * Total Return
             * @description Compounded total return of the replayed portfolio as a decimal fraction (0.5 = +50%), never 0-100.
             */
            total_return: number;
            /**
             * Beta
             * @description Portfolio beta vs benchmark over aligned daily returns (unitless).
             */
            beta: number;
            /**
             * Correlation
             * @description Pearson correlation vs benchmark over aligned daily returns (-1..1).
             */
            correlation: number;
            /**
             * Diversification Ratio
             * @description Weighted-average asset volatility divided by portfolio volatility at the effective initial weights; >= 1 for long-only portfolios (unitless).
             */
            diversification_ratio: number;
            max_drawdown: components["schemas"]["DrawdownOut"];
            best_day: components["schemas"]["DatedValue"];
            worst_day: components["schemas"]["DatedValue"];
        };
        /**
         * PositionBody
         * @description Quantity/acquisition-price payload for the position upsert (PUT).
         */
        PositionBody: {
            /**
             * Quantity
             * @description Shares/units held; > 0.
             */
            quantity: number;
            /**
             * Acq Price
             * @description Acquisition price per share/unit; null = unknown (P&L renders null).
             */
            acq_price?: number | null;
        };
        /**
         * PositionCreate
         * @description One position in the create-portfolio payload.
         */
        PositionCreate: {
            /**
             * Quantity
             * @description Shares/units held; > 0.
             */
            quantity: number;
            /**
             * Acq Price
             * @description Acquisition price per share/unit; null = unknown (P&L renders null).
             */
            acq_price?: number | null;
            /**
             * Ticker
             * @description Instrument ticker (normalized to uppercase).
             */
            ticker: string;
        };
        /**
         * PositionIn
         * @description One requested position: a ticker plus EITHER a weight OR a quantity.
         *
         *     Which field is required depends on the request ``mode`` (cross-checked at
         *     the request level): mode=weights demands ``weight``, mode=quantities
         *     demands ``quantity``.
         */
        PositionIn: {
            /**
             * Ticker
             * @description Instrument ticker (normalized to uppercase).
             */
            ticker: string;
            /**
             * Weight
             * @description Target weight as a decimal fraction (0.5 = 50%), never 0-100; > 0.
             */
            weight?: number | null;
            /**
             * Quantity
             * @description Number of shares/units held; > 0.
             */
            quantity?: number | null;
        };
        /**
         * PositionOut
         * @description One persisted position.
         */
        PositionOut: {
            /** Ticker */
            ticker: string;
            /** Quantity */
            quantity: number;
            /** Acq Price */
            acq_price: number | null;
        };
        /**
         * PositionOverview
         * @description One render-ready overview row; the backend computes ALL finance.
         */
        PositionOverview: {
            /** Ticker */
            ticker: string;
            /**
             * Name
             * @description Display name from the instruments cache.
             */
            name: string | null;
            /** Quantity */
            quantity: number;
            /**
             * Acq Price
             * @description Acquisition price per share/unit; null = unknown.
             */
            acq_price: number | null;
            /**
             * Last Close
             * @description Most recent EOD close, currency units.
             */
            last_close: number;
            /**
             * Prev Close
             * @description Second-most-recent EOD close; null when only one row exists.
             */
            prev_close: number | null;
            /**
             * Change
             * @description last_close - prev_close, currency units; null without prev_close.
             */
            change: number | null;
            /**
             * Change Pct
             * @description change / prev_close as a decimal fraction (0.05 = 5%), never 0-100; null without prev_close.
             */
            change_pct: number | null;
            /**
             * Market Value
             * @description quantity * last_close, currency units.
             */
            market_value: number;
            /**
             * Cost Basis
             * @description quantity * acq_price, currency units; null when acq_price is unknown.
             */
            cost_basis: number | null;
            /**
             * Pnl
             * @description market_value - cost_basis, currency units; null when acq_price is unknown.
             */
            pnl: number | null;
            /**
             * Pnl Pct
             * @description pnl / cost_basis as a decimal fraction (0.10 = 10%), never 0-100; null when acq_price is unknown.
             */
            pnl_pct: number | null;
            /**
             * As Of
             * Format: date
             * @description Date of last_close.
             */
            as_of: string;
        };
        /**
         * PricePoint
         * @description One EOD bar in a price series response.
         */
        PricePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /** Adj Close */
            adj_close: number;
            /** Div Cash */
            div_cash: number;
            /** Split Factor */
            split_factor: number;
        };
        /**
         * PriceSeriesResponse
         * @description EOD price series for one ticker over [start_date, end_date].
         */
        PriceSeriesResponse: {
            /** Ticker */
            ticker: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Count */
            count: number;
            /** Prices */
            prices: components["schemas"]["PricePoint"][];
        };
        /**
         * RegressionOut
         * @description OLS regression of y on x over the aligned daily returns.
         */
        RegressionOut: {
            /**
             * Beta
             * @description Slope: cov(x, y) / var(x) over aligned daily returns (engine beta).
             */
            beta: number;
            /**
             * Alpha
             * @description Intercept in DAILY decimal-return units: mean_y - beta * mean_x, derived from the engine beta (NOT annualized).
             */
            alpha: number;
            /**
             * R
             * @description Pearson correlation of the aligned returns (-1..1).
             */
            r: number;
            /**
             * N Points
             * @description Number of aligned daily return pairs.
             */
            n_points: number;
        };
        /**
         * RiskContributionOut
         * @description One asset's share of total portfolio risk (CTR convention).
         */
        RiskContributionOut: {
            /** Ticker */
            ticker: string;
            /**
             * Contribution
             * @description Fraction of TOTAL portfolio risk (decimal fraction; all contributions sum to 1), evaluated at the effective initial weights.
             */
            contribution: number;
        };
        /**
         * ScenarioParams
         * @description Echo of the resolved scenario parameters.
         */
        ScenarioParams: {
            /** Portfolio Id */
            portfolio_id: number;
            /**
             * Name
             * @description Portfolio display name.
             */
            name: string;
            /**
             * Start Date
             * Format: date
             * @description First analyzed trading day (first date where ALL holdings have data within the requested window).
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description Last analyzed trading day.
             */
            end_date: string;
            /**
             * Cash
             * @description Uninvested cash balance, in currency units.
             */
            cash: number;
            /**
             * Frequency
             * @description Grid of ALL emitted line series: daily, or weekly (W-FRI last-of-week) when the window exceeds the daily bounding threshold. Statistics stay daily.
             * @enum {string}
             */
            frequency: "daily" | "weekly";
        };
        /**
         * ScenarioRequest
         * @description Historical replay of a persisted portfolio over [start_date, end_date].
         *
         *     Replay semantics: the portfolio's CURRENT quantities (and current cash)
         *     are held fixed over the whole window — "what would this portfolio have
         *     done over that period?", not a reconstruction of past trades.
         */
        ScenarioRequest: {
            /**
             * Start Date
             * Format: date
             * @description Window start (inclusive).
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description Window end (inclusive).
             */
            end_date: string;
            /**
             * Portfolio Id
             * @description Persisted portfolio id.
             */
            portfolio_id: number;
        };
        /**
         * ScenarioResponse
         * @description Render-ready scenario payload — historical replay of a persisted portfolio.
         *
         *     The portfolio's CURRENT quantities are held fixed (buy-and-hold) over the
         *     window; uninvested cash is a constant. All series share the same date grid
         *     (daily, or W-FRI weekly when bounded — see ``params.frequency``). The
         *     backend computes ALL finance; the frontend only draws.
         */
        ScenarioResponse: {
            params: components["schemas"]["ScenarioParams"];
            /**
             * Nav Cash
             * @description Stacked value series in currency units: one per position, plus a constant "CASH" series when cash > 0, plus "TOTAL" (positions + cash).
             */
            nav_cash: components["schemas"]["StackedSeries"][];
            /**
             * Weights Percent
             * @description Weight evolution as decimal fractions (0.5 = 50%, the frontend formats to 0-100): one per position, plus "CASH" when cash > 0. Rows sum to 1 across series per date. No "TOTAL" series (it would be constant 1).
             */
            weights_percent: components["schemas"]["StackedSeries"][];
            /**
             * Asset Performance
             * @description Cumulative return rebased to 0.0 at the window start, decimal fractions: one per position, plus "TOTAL" (cash-inclusive portfolio).
             */
            asset_performance: components["schemas"]["StackedSeries"][];
            /** @description Histogram of the portfolio's DAILY returns (cash-inclusive total). */
            histogram: components["schemas"]["HistogramOut"];
            statistics: components["schemas"]["ScenarioStatistics"];
        };
        /**
         * ScenarioStatistics
         * @description Typed statistics rail of the scenario — computed on DAILY data even when
         *     the line series are weekly-bounded. NAV figures include cash; returns are
         *     daily simple returns of the cash-inclusive total value.
         */
        ScenarioStatistics: {
            /**
             * Start Date
             * Format: date
             * @description First analyzed trading day.
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description Last analyzed trading day.
             */
            end_date: string;
            /**
             * Start Nav
             * @description Total value (positions + cash) at start_date.
             */
            start_nav: number;
            /**
             * End Nav
             * @description Total value (positions + cash) at end_date.
             */
            end_nav: number;
            max_nav: components["schemas"]["DatedNav"];
            min_nav: components["schemas"]["DatedNav"];
            /** @description Best daily return and its date. */
            max_return: components["schemas"]["DatedValue"];
            /** @description Worst daily return and its date. */
            min_return: components["schemas"]["DatedValue"];
            /**
             * Annualized Volatility
             * @description Annualized volatility of daily returns, decimal fraction (0.25 = 25%).
             */
            annualized_volatility: number;
            /**
             * Var 95
             * @description Historical 1-day VaR at 95% as a POSITIVE decimal fraction.
             */
            var_95: number;
            /**
             * Var 99
             * @description Historical 1-day VaR at 99% as a POSITIVE decimal fraction.
             */
            var_99: number;
        };
        /**
         * StackedSeries
         * @description One series of a stacked chart: a position ticker, "CASH", or "TOTAL".
         */
        StackedSeries: {
            /**
             * Ticker
             * @description Position ticker, "CASH" (constant cash balance), or "TOTAL".
             */
            ticker: string;
            /**
             * Points
             * @description [date, value] points; the value scale is documented on the field that carries the series list.
             */
            points: [
                string,
                number
            ][];
        };
        /**
         * StockAnalysisResponse
         * @description Render-ready single-call payload for the stock analysis page.
         *
         *     The backend computes ALL finance; the frontend only draws. Every
         *     fractional field is a decimal fraction (0.05 = 5%), never 0-100.
         *     Rolling series are warmed up on a pre-range pad and then sliced to the
         *     visible range with NaN rows dropped, so they cover the visible range
         *     from (approximately) its first trading day.
         */
        StockAnalysisResponse: {
            params: components["schemas"]["AnalysisParams"];
            header: components["schemas"]["AnalysisHeader"];
            /** Candles */
            candles: components["schemas"]["Candle"][];
            cumulative_returns: components["schemas"]["CumulativeReturns"];
            /**
             * Rolling Volatility
             * @description [date, annualized volatility] points, decimal fractions (0.25 = 25%); in-range dates only, NaN warm-up rows dropped.
             */
            rolling_volatility: [
                string,
                number
            ][];
            /**
             * Rolling Beta
             * @description [date, beta vs benchmark] points (unitless); in-range, NaN rows dropped.
             */
            rolling_beta: [
                string,
                number
            ][];
            /**
             * Rolling Correlation
             * @description [date, correlation vs benchmark] points (-1..1); in-range, NaN rows dropped.
             */
            rolling_correlation: [
                string,
                number
            ][];
            histogram: components["schemas"]["HistogramOut"];
            stats: components["schemas"]["AnalysisStats"];
        };
        /**
         * StockCorrelationRequest
         * @description Pairwise correlation of a portfolio's holdings over a trailing window.
         */
        StockCorrelationRequest: {
            /**
             * Portfolio Id
             * @description Persisted portfolio id.
             */
            portfolio_id: number;
            /**
             * Window
             * @description Trailing window length in TRADING days of returns (window + 1 closes are required).
             * @default 63
             */
            window: number;
            /**
             * End Date
             * @description Window end; defaults to the latest available trading day.
             */
            end_date?: string | null;
        };
        /**
         * StockCorrelationResponse
         * @description Pairwise Pearson correlation matrix of the holdings' daily returns.
         */
        StockCorrelationResponse: {
            /**
             * Tickers
             * @description Row/column order of the matrix.
             */
            tickers: string[];
            /**
             * Matrix
             * @description Row-major square matrix (-1..1); symmetric with unit diagonal.
             */
            matrix: number[][];
            /**
             * Window
             * @description Number of TRADING-day returns used (exactly).
             */
            window: number;
            /**
             * As Of
             * Format: date
             * @description Last trading day of the window (the latest date COMMON to all holdings, capped at the requested end_date).
             */
            as_of: string;
        };
        /**
         * TickerRef
         * @description Pseudo-asset reference: a plain instrument ticker.
         */
        TickerRef: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "ticker";
            /**
             * Ticker
             * @description Instrument ticker (normalized to uppercase).
             */
            ticker: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_price_series_stocks__ticker__prices_get: {
        parameters: {
            query?: {
                /** @description Defaults to end_date - 365d */
                start_date?: string | null;
                /** @description Defaults to today */
                end_date?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_analysis_stocks__ticker__analysis_get: {
        parameters: {
            query?: {
                /** @description Visible-range preset; MAX = full available history. */
                range?: "1M" | "6M" | "1Y" | "5Y" | "MAX";
                /** @description Benchmark ticker for beta/correlation/relative series. */
                benchmark?: string;
                /** @description Rolling window in TRADING days (10..252). */
                window?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticker_news_stocks__ticker__news_get: {
        parameters: {
            query?: {
                /** @description Max articles returned. */
                limit?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_portfolio_portfolio_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_portfolios_portfolios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioListItem"][];
                };
            };
        };
    };
    create_portfolio_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_portfolios__portfolio_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_portfolios__portfolio_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_portfolio_portfolios__portfolio_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_position_portfolios__portfolio_id__positions__ticker__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                ticker: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PositionBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PositionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_position_portfolios__portfolio_id__positions__ticker__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_overview_portfolios__portfolio_id__overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portfolio_news_portfolios__portfolio_id__news_get: {
        parameters: {
            query?: {
                /** @description Max articles returned. */
                limit?: number;
            };
            header?: never;
            path: {
                portfolio_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioNewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_statistics_scenario_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    beta_scatter_statistics_beta_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BetaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BetaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rolling_correlation_statistics_correlation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrelationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorrelationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_correlation_statistics_stock_correlation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockCorrelationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockCorrelationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
