/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Check service health including database connectivity.
         *
         *     Returns HTTP 503 with an error detail if the database is unreachable.
         *     Never returns 200 with a degraded payload — fail loud.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{ticker}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Price Series
         * @description Return the EOD price series for *ticker*, ingesting on demand if cold/stale.
         */
        get: operations["get_price_series_stocks__ticker__prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{ticker}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stock Analysis
         * @description Render-ready analysis payload for one ticker — single call, no frontend finance.
         *
         *     The visible range ends at the last trading day available for the ticker;
         *     rolling series are warmed up on a pre-range pad and sliced back to the
         *     visible range. All fractional fields are decimal fractions (0.05 = 5%).
         */
        get: operations["get_stock_analysis_stocks__ticker__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks/{ticker}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ticker News
         * @description Per-ticker news, newest first — DB-first with a declared degrade path.
         *
         *     Degrade decision (deliberate, documented): news is a SECONDARY panel.  If
         *     the Tiingo refresh fails but the DB holds cached articles, serve them with
         *     ``stale=true`` and log the error — a declared degradation, NOT a silent
         *     fallback.  If the refresh fails and the cache is empty, fail loud with the
         *     usual 503/502 mapping.
         *
         *     Unknown tickers do not 404 here: Tiingo's news feed has no per-ticker
         *     existence check, and "no news" is a legitimate ``count=0`` response.  The
         *     ticker format is sanity-checked (alphanumeric + ".-", at most 10 chars)
         *     to reject absurd path segments with 422.
         */
        get: operations["get_ticker_news_stocks__ticker__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Portfolio
         * @description Render-ready analysis payload for an ad-hoc portfolio — single call.
         *
         *     Buy-and-hold replay (NAV, returns-based stats, benchmark comparison) plus
         *     covariance decomposition (risk contributions, diversification ratio,
         *     correlation matrix) — see ``app.analytics.portfolio`` for the two-views
         *     semantics. All fractional fields are decimal fractions (0.05 = 5%).
         */
        post: operations["analyze_portfolio_portfolio_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AllocationOut
         * @description Resolved allocation at the first analyzed date (the replay strike point).
         */
        AllocationOut: {
            /** Positions */
            positions: components["schemas"]["AllocationPosition"][];
            /**
             * Initial Nav
             * @description Sum of initial position values, in currency units.
             */
            initial_nav: number;
        };
        /**
         * AllocationPosition
         * @description One position of the resolved allocation at the first date.
         */
        AllocationPosition: {
            /** Ticker */
            ticker: string;
            /**
             * Weight
             * @description Effective initial weight as a decimal fraction (0.5 = 50%), never 0-100. For mode='weights' the (renormalized) requested weight; for mode='quantities' the initial-date value weight.
             */
            weight: number;
            /**
             * Initial Value
             * @description Position value at the first date, in currency units.
             */
            initial_value: number;
        };
        /**
         * AnalysisHeader
         * @description Render-ready header strip values (RAW, un-adjusted prices).
         */
        AnalysisHeader: {
            /** Ticker */
            ticker: string;
            /**
             * Name
             * @description Instrument name from Tiingo metadata, if known.
             */
            name: string | null;
            /**
             * Last Close
             * @description Most recent RAW close price (currency units).
             */
            last_close: number;
            /**
             * Prev Close
             * @description Previous trading day's RAW close price (currency units).
             */
            prev_close: number;
            /**
             * Change
             * @description last_close - prev_close, in currency units (not a fraction).
             */
            change: number;
            /**
             * Change Pct
             * @description One-day change as a decimal fraction (0.05 = 5%), never 0-100.
             */
            change_pct: number;
            /**
             * As Of
             * Format: date
             * @description Date of last_close.
             */
            as_of: string;
        };
        /**
         * AnalysisParams
         * @description Echo of the resolved request parameters.
         */
        AnalysisParams: {
            /**
             * Range
             * @description Requested range preset.
             * @enum {string}
             */
            range: "1M" | "6M" | "1Y" | "5Y" | "MAX";
            /**
             * Benchmark
             * @description Benchmark ticker used for beta/correlation/relative series.
             */
            benchmark: string;
            /**
             * Window
             * @description Rolling window length in TRADING days.
             */
            window: number;
            /**
             * Start Date
             * Format: date
             * @description Resolved visible-range start (inclusive for prices/candles).
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description Resolved visible-range end — the last trading day available for the ticker.
             */
            end_date: string;
        };
        /**
         * AnalysisStats
         * @description Point statistics over IN-RANGE returns only (the rolling warm-up pad
         *     is never included). Beta/correlation are versus the benchmark on the
         *     aligned in-range date grid.
         */
        AnalysisStats: {
            /**
             * Annualized Volatility
             * @description Annualized volatility as a decimal fraction (0.25 = 25%), never 0-100.
             */
            annualized_volatility: number;
            /**
             * Var 95
             * @description Historical 1-day VaR at 95% as a POSITIVE decimal fraction (0.02 = 5% of days lose more than 2%), never 0-100.
             */
            var_95: number;
            /**
             * Var 99
             * @description Historical 1-day VaR at 99% as a POSITIVE decimal fraction, never 0-100.
             */
            var_99: number;
            /**
             * Cvar 95
             * @description Historical 1-day CVaR (expected shortfall) at 95% as a POSITIVE decimal fraction, never 0-100.
             */
            cvar_95: number;
            /**
             * Total Return
             * @description Compounded in-range total return as a decimal fraction (0.5 = +50%), never 0-100.
             */
            total_return: number;
            /**
             * Beta
             * @description Beta vs benchmark over in-range aligned returns (unitless).
             */
            beta: number;
            /**
             * Correlation
             * @description Pearson correlation vs benchmark over in-range aligned returns (-1..1).
             */
            correlation: number;
            max_drawdown: components["schemas"]["DrawdownOut"];
            best_day: components["schemas"]["DatedValue"];
            worst_day: components["schemas"]["DatedValue"];
        };
        /**
         * BenchmarkComparison
         * @description Cumulative return of the portfolio vs the benchmark, rebased to 0.
         *
         *     Both series share the same aligned date grid and start at exactly 0.0 on
         *     the same first date. Values are decimal fractions (0.05 = 5%), never 0-100.
         */
        BenchmarkComparison: {
            /**
             * Portfolio
             * @description [date, cumulative return] points; decimal fractions (0.05 = 5%).
             */
            portfolio: [
                string,
                number
            ][];
            /**
             * Benchmark
             * @description [date, cumulative return] points; decimal fractions (0.05 = 5%).
             */
            benchmark: [
                string,
                number
            ][];
        };
        /**
         * Candle
         * @description One OHLCV candle built from RAW (un-adjusted) prices.
         *
         *     Daily for ranges up to 5Y; weekly (W-FRI buckets: open=first, high=max,
         *     low=min, close=last, volume=sum) for range MAX.
         */
        Candle: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
        };
        /**
         * CorrelationMatrixOut
         * @description Pairwise Pearson correlation of per-asset daily returns.
         */
        CorrelationMatrixOut: {
            /**
             * Tickers
             * @description Row/column order of the matrix.
             */
            tickers: string[];
            /**
             * Matrix
             * @description Row-major square matrix (-1..1); symmetric with unit diagonal.
             */
            matrix: number[][];
        };
        /**
         * CumulativeReturns
         * @description Cumulative return series rebased to 0 at the first in-range date.
         *
         *     Asset and benchmark share the same date grid (aligned on common trading
         *     days before slicing). Values are decimal fractions (0.05 = 5%), never
         *     0-100; both series start at exactly 0.0 on the same first date.
         */
        CumulativeReturns: {
            /**
             * Asset
             * @description [date, cumulative return] points; decimal fractions (0.05 = 5%).
             */
            asset: [
                string,
                number
            ][];
            /**
             * Benchmark
             * @description [date, cumulative return] points; decimal fractions (0.05 = 5%).
             */
            benchmark: [
                string,
                number
            ][];
        };
        /**
         * DatedValue
         * @description A single dated return observation.
         */
        DatedValue: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Value
             * @description Daily return as a decimal fraction (0.05 = 5%), never 0-100.
             */
            value: number;
        };
        /**
         * DrawdownOut
         * @description Maximum drawdown of the in-range ADJUSTED close series.
         */
        DrawdownOut: {
            /**
             * Depth
             * @description NEGATIVE decimal fraction (-0.35 = 35% peak-to-trough loss), never 0-100.
             */
            depth: number;
            /**
             * Peak Date
             * Format: date
             */
            peak_date: string;
            /**
             * Trough Date
             * Format: date
             */
            trough_date: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /**
         * HistogramOut
         * @description Histogram of in-range daily returns.
         */
        HistogramOut: {
            /**
             * Bin Edges
             * @description len(counts)+1 edges in daily-return units, decimal fractions (0.05 = 5%).
             */
            bin_edges: number[];
            /**
             * Counts
             * @description Observations per bin.
             */
            counts: number[];
            /**
             * Counts Normalized
             * @description Each count divided by the maximum count (0-1), for direct bar heights.
             */
            counts_normalized: number[];
        };
        /**
         * NewsArticle
         * @description One news article linked to the requested ticker.
         */
        NewsArticle: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Source */
            source: string | null;
            /** Description */
            description: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /**
         * NewsResponse
         * @description News articles for one ticker, newest first.
         *
         *     ``stale`` is True when the Tiingo refresh failed but cached articles were
         *     served — a declared degradation, never a silent fallback.
         */
        NewsResponse: {
            /** Ticker */
            ticker: string;
            /** Count */
            count: number;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Items */
            items: components["schemas"]["NewsArticle"][];
        };
        /**
         * PortfolioAnalysisRequest
         * @description Ad-hoc portfolio definition to replay and decompose (no persistence).
         */
        PortfolioAnalysisRequest: {
            /**
             * Positions
             * @description Between 2 and 50 positions.
             */
            positions: components["schemas"]["PositionIn"][];
            /**
             * Mode
             * @description 'weights' = every position carries a weight; 'quantities' = share counts.
             * @enum {string}
             */
            mode: "weights" | "quantities";
            /**
             * Range
             * @description Visible-range preset; MAX = full COMMON history.
             * @default 1Y
             * @enum {string}
             */
            range: "1M" | "6M" | "1Y" | "5Y" | "MAX";
            /**
             * Benchmark
             * @description Benchmark ticker for the comparison series and beta/correlation. May coincide with a position.
             * @default SPY
             */
            benchmark: string;
        };
        /**
         * PortfolioAnalysisResponse
         * @description Render-ready single-call payload for the static portfolio page.
         *
         *     Two views, two questions (see ``app.analytics.portfolio``): ``nav``,
         *     ``benchmark_comparison`` and the return-based ``stats`` are a buy-and-hold
         *     REPLAY (fixed quantities, weights drift); ``risk_contributions`` and
         *     ``diversification_ratio`` are a covariance DECOMPOSITION at the effective
         *     initial weights held constant. The backend computes ALL finance; the
         *     frontend only draws. Every fractional field is a decimal fraction
         *     (0.05 = 5%), never 0-100.
         */
        PortfolioAnalysisResponse: {
            params: components["schemas"]["PortfolioParams"];
            allocation: components["schemas"]["AllocationOut"];
            /**
             * Nav
             * @description [date, NAV] points in currency units; starts at initial_nav. Daily up to 5Y; weekly (W-FRI, last-of-week) for range MAX. Shares the same date grid as benchmark_comparison (sliced to the portfolio–benchmark aligned index) so all line series can be plotted on a single x-axis. Stats are computed on the full position-grid NAV (before the benchmark alignment slice) — they describe the portfolio, not the comparison chart.
             */
            nav: [
                string,
                number
            ][];
            benchmark_comparison: components["schemas"]["BenchmarkComparison"];
            stats: components["schemas"]["PortfolioStats"];
            correlation_matrix: components["schemas"]["CorrelationMatrixOut"];
            /**
             * Risk Contributions
             * @description Per-asset fractions of total risk; they sum to 1.
             */
            risk_contributions: components["schemas"]["RiskContributionOut"][];
            histogram: components["schemas"]["HistogramOut"];
        };
        /**
         * PortfolioParams
         * @description Echo of the resolved request parameters.
         */
        PortfolioParams: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "weights" | "quantities";
            /**
             * Range
             * @description Requested range preset.
             * @enum {string}
             */
            range: "1M" | "6M" | "1Y" | "5Y" | "MAX";
            /**
             * Benchmark
             * @description Benchmark ticker used for the comparison series.
             */
            benchmark: string;
            /**
             * Start Date
             * Format: date
             * @description First trading day of the analyzed window (first date where ALL position tickers have data).
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             * @description Last trading day of the analyzed window — the most recent date COMMON to all requested symbols (positions + benchmark). One stale symbol (a ticker whose last available EOD row lags the others) moves this date back for everyone; end = min(last_available_date per symbol).
             */
            end_date: string;
            /**
             * Initial Nav
             * @description Portfolio value at start_date, in currency units. 10000 for mode='weights' (notional); the actual position value for mode='quantities'.
             */
            initial_nav: number;
        };
        /**
         * PortfolioStats
         * @description Point statistics over the portfolio's daily returns in the analyzed
         *     window. Beta/correlation are versus the benchmark on the aligned date
         *     grid; the diversification ratio is evaluated at the effective initial
         *     weights (decomposition view).
         */
        PortfolioStats: {
            /**
             * Annualized Volatility
             * @description Annualized volatility as a decimal fraction (0.25 = 25%), never 0-100.
             */
            annualized_volatility: number;
            /**
             * Var 95
             * @description Historical 1-day VaR at 95% as a POSITIVE decimal fraction (0.02 = 5% of days lose more than 2%), never 0-100.
             */
            var_95: number;
            /**
             * Var 99
             * @description Historical 1-day VaR at 99% as a POSITIVE decimal fraction, never 0-100.
             */
            var_99: number;
            /**
             * Cvar 95
             * @description Historical 1-day CVaR (expected shortfall) at 95% as a POSITIVE decimal fraction, never 0-100.
             */
            cvar_95: number;
            /**
             * Total Return
             * @description Compounded total return of the replayed portfolio as a decimal fraction (0.5 = +50%), never 0-100.
             */
            total_return: number;
            /**
             * Beta
             * @description Portfolio beta vs benchmark over aligned daily returns (unitless).
             */
            beta: number;
            /**
             * Correlation
             * @description Pearson correlation vs benchmark over aligned daily returns (-1..1).
             */
            correlation: number;
            /**
             * Diversification Ratio
             * @description Weighted-average asset volatility divided by portfolio volatility at the effective initial weights; >= 1 for long-only portfolios (unitless).
             */
            diversification_ratio: number;
            max_drawdown: components["schemas"]["DrawdownOut"];
            best_day: components["schemas"]["DatedValue"];
            worst_day: components["schemas"]["DatedValue"];
        };
        /**
         * PositionIn
         * @description One requested position: a ticker plus EITHER a weight OR a quantity.
         *
         *     Which field is required depends on the request ``mode`` (cross-checked at
         *     the request level): mode=weights demands ``weight``, mode=quantities
         *     demands ``quantity``.
         */
        PositionIn: {
            /**
             * Ticker
             * @description Instrument ticker (normalized to uppercase).
             */
            ticker: string;
            /**
             * Weight
             * @description Target weight as a decimal fraction (0.5 = 50%), never 0-100; > 0.
             */
            weight?: number | null;
            /**
             * Quantity
             * @description Number of shares/units held; > 0.
             */
            quantity?: number | null;
        };
        /**
         * PricePoint
         * @description One EOD bar in a price series response.
         */
        PricePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /** Adj Close */
            adj_close: number;
            /** Div Cash */
            div_cash: number;
            /** Split Factor */
            split_factor: number;
        };
        /**
         * PriceSeriesResponse
         * @description EOD price series for one ticker over [start_date, end_date].
         */
        PriceSeriesResponse: {
            /** Ticker */
            ticker: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Count */
            count: number;
            /** Prices */
            prices: components["schemas"]["PricePoint"][];
        };
        /**
         * RiskContributionOut
         * @description One asset's share of total portfolio risk (CTR convention).
         */
        RiskContributionOut: {
            /** Ticker */
            ticker: string;
            /**
             * Contribution
             * @description Fraction of TOTAL portfolio risk (decimal fraction; all contributions sum to 1), evaluated at the effective initial weights.
             */
            contribution: number;
        };
        /**
         * StockAnalysisResponse
         * @description Render-ready single-call payload for the stock analysis page.
         *
         *     The backend computes ALL finance; the frontend only draws. Every
         *     fractional field is a decimal fraction (0.05 = 5%), never 0-100.
         *     Rolling series are warmed up on a pre-range pad and then sliced to the
         *     visible range with NaN rows dropped, so they cover the visible range
         *     from (approximately) its first trading day.
         */
        StockAnalysisResponse: {
            params: components["schemas"]["AnalysisParams"];
            header: components["schemas"]["AnalysisHeader"];
            /** Candles */
            candles: components["schemas"]["Candle"][];
            cumulative_returns: components["schemas"]["CumulativeReturns"];
            /**
             * Rolling Volatility
             * @description [date, annualized volatility] points, decimal fractions (0.25 = 25%); in-range dates only, NaN warm-up rows dropped.
             */
            rolling_volatility: [
                string,
                number
            ][];
            /**
             * Rolling Beta
             * @description [date, beta vs benchmark] points (unitless); in-range, NaN rows dropped.
             */
            rolling_beta: [
                string,
                number
            ][];
            /**
             * Rolling Correlation
             * @description [date, correlation vs benchmark] points (-1..1); in-range, NaN rows dropped.
             */
            rolling_correlation: [
                string,
                number
            ][];
            histogram: components["schemas"]["HistogramOut"];
            stats: components["schemas"]["AnalysisStats"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_price_series_stocks__ticker__prices_get: {
        parameters: {
            query?: {
                /** @description Defaults to end_date - 365d */
                start_date?: string | null;
                /** @description Defaults to today */
                end_date?: string | null;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stock_analysis_stocks__ticker__analysis_get: {
        parameters: {
            query?: {
                /** @description Visible-range preset; MAX = full available history. */
                range?: "1M" | "6M" | "1Y" | "5Y" | "MAX";
                /** @description Benchmark ticker for beta/correlation/relative series. */
                benchmark?: string;
                /** @description Rolling window in TRADING days (10..252). */
                window?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticker_news_stocks__ticker__news_get: {
        parameters: {
            query?: {
                /** @description Max articles returned. */
                limit?: number;
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_portfolio_portfolio_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
