-- portfolio_constraints: per-portfolio construction limits (Sprint B, Task 2).
--
-- Sprint B persists the constraints a portfolio was built under. Two tables,
-- both single-tenant (scoped by portfolio_id, no owner column — same as the
-- portfolio tables):
--   portfolio_constraint_set  — header, 1:1 with a portfolio; scalar limits
--                               (cap / min_weight / overlap_cap), each nullable.
--   portfolio_class_limits    — zero-or-more per-asset-class min/max weight
--                               bounds; one row per (portfolio, asset_class).
-- Both FK to portfolios.id with ON DELETE CASCADE (deleting a portfolio drops
-- its constraints). PKs follow the portfolio-family int convention.
--
-- Constraint/index names match the SQLAlchemy naming convention
-- (app/models/base.py) so the ORM model and this DDL stay in lockstep:
--   pk_portfolio_constraint_set, fk_portfolio_constraint_set_portfolio_id_portfolios,
--   pk_portfolio_class_limits, fk_portfolio_class_limits_portfolio_id_portfolios,
--   uq_portfolio_class_limits_portfolio_id_asset_class,
--   ck_portfolio_class_limits_asset_class,
--   ix_portfolio_class_limits_portfolio_id.

CREATE TABLE IF NOT EXISTS portfolio_constraint_set (
    portfolio_id integer     NOT NULL,
    cap          double precision,
    min_weight   double precision,
    overlap_cap  double precision,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_portfolio_constraint_set PRIMARY KEY (portfolio_id),
    CONSTRAINT fk_portfolio_constraint_set_portfolio_id_portfolios
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS portfolio_class_limits (
    id           integer     GENERATED BY DEFAULT AS IDENTITY,
    portfolio_id integer     NOT NULL,
    asset_class  text        NOT NULL,
    min_weight   double precision,
    max_weight   double precision,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pk_portfolio_class_limits PRIMARY KEY (id),
    CONSTRAINT fk_portfolio_class_limits_portfolio_id_portfolios
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id) ON DELETE CASCADE,
    CONSTRAINT uq_portfolio_class_limits_portfolio_id_asset_class
        UNIQUE (portfolio_id, asset_class),
    CONSTRAINT ck_portfolio_class_limits_asset_class
        CHECK (asset_class IN
            ('equity', 'fixed_income', 'cash', 'alternatives', 'multi_asset'))
);

CREATE INDEX IF NOT EXISTS ix_portfolio_class_limits_portfolio_id
    ON portfolio_class_limits (portfolio_id);
